#!/usr/bin/env bash
#
# ==============================================================================
# HarderAdmin
# config/task_status.conf
# ==============================================================================
#

readonly HA_TASK_READY=0
readonly HA_TASK_COMPLETED=10
readonly HA_TASK_BLOCKED=20
readonly HA_TASK_ERROR=30